name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Running Unit Tests with Maven
        run: mvn test

  functional-test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Running Functional Tests with Maven
        run: mvn clean test -Pfunctional-test surefire-report:report site
      - name: Test Report Generate
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./target/site
            ./target/surefire-reports/*.dumpstream

  build:
    name: Build and Sonar Cloud
    needs:
      - unit-test
      - functional-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and SonarCloud Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=arthurboeck_covid-brazil-data-api